version: '3.8'

services:
  nexus_neo4j:
    image: neo4j:latest
    container_name: nexus_neo4j
    ports:
      - "7474:7474" # Browser GUI
      - "7687:7687" # Bolt protocol
    environment:
      - NEO4J_AUTH=neo4j/password
      - NEO4J_PLUGINS=["apoc"]
    volumes:
      - ./data:/data
      - ./logs:/logs
    networks:
      - nexus_net

  nexus_backend:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: nexus_backend
    ports:
      - "8000:8000"
    environment:
      - NEO4J_URI=bolt://nexus_neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=password
    env_file:
      - .env
    depends_on:
      - nexus_neo4j
    networks:
      - nexus_net

  nexus_frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile.ui
    container_name: nexus_frontend
    ports:
      - "80:80"
    depends_on:
      - nexus_backend
    networks:
      - nexus_net

  juiceshop:
    image: bkimminich/juice-shop:latest
    container_name: juiceshop
    ports:
      - "4000:3000"
    networks:
      - nexus_net

networks:
  nexus_net:
    driver: bridge
